import { MODULES } from "../constants/modules";
import type { BackgroundType, Direction, Protocol } from "../types";

const optokineticVideos: Array<[number, string, BackgroundType, Direction]> = [
  [1, "Vertical Distortion Moving Up", "stripes", "up"],
  [2, "Vertical Distortion Going Down", "stripes", "down"],
  [3, "Horizontal Distortion Going Left", "stripes", "left"],
  [4, "Horizontal Distortion Going Right", "stripes", "right"],
  [5, "Chequered Board Jiggle", "checkerboard", "jiggle"],
  [6, "Checkerboard Warp", "checkerboard", "warp"],
  [7, "Diagonal Distortion Going To Top Left", "stripes", "top-left"],
  [8, "Diagonal Distortion Going To Bottom Left", "stripes", "bottom-left"],
  [9, "Diagonal Distortion Going To Top Right", "stripes", "top-right"],
  [10, "Diagonal Distortion Going To Bottom Right", "stripes", "bottom-right"],
  [11, "Arrows Moving Up", "arrows", "up"],
  [12, "Arrows Moving Down", "arrows", "down"],
  [13, "V Moving Up", "letterV", "up"],
  [14, "V Moving Down", "letterV", "down"],
  [15, "Horizontal Diverging Distortions", "divergentStripes", "right"],
  [16, "Horizontal Converging Distortions", "convergentStripes", "left"],
  [17, "Vertical Diverging Distortions", "divergentStripes", "down"],
  [18, "Vertical Converging Distortions", "convergentStripes", "up"],
  [19, "Multiple Distortions Intersecting", "intersectingStripes", "multi"],
  [72, "Horizontal Distortion", "stripes", "right"],
  [73, "Vertical Distortion", "stripes", "down"],
];

const vor2Videos: Array<[number, string, BackgroundType, Direction, number]> = [
  [20, "Vertical Distortion Moving Up · RVO x2 Slow", "stripes", "up", 1],
  [21, "Vertical Distortion Moving Down · RVO x2 Slow", "stripes", "down", 1],
  [22, "Horizontal Distortion Moving Right · RVO x2 Slow", "stripes", "right", 1],
  [23, "Horizontal Distortion Moving Left · RVO x2 Slow", "stripes", "left", 1],
  [24, "Chequered Board Jiggle · RVO x2 Slow", "checkerboard", "jiggle", 1],
  [25, "Diagonal Distortion Moving Top Right · RVO x2 Slow", "stripes", "top-right", 1],
  [26, "Diagonal Distortion Moving Bottom Left · RVO x2 Slow", "stripes", "bottom-left", 1],
  [27, "Diagonal Distortion Moving Top Left · RVO x2 Slow", "stripes", "top-left", 1],
  [28, "Diagonal Distortion Moving Bottom Right · RVO x2 Slow", "stripes", "bottom-right", 1],
  [29, "Arrows Moving Up · RVO x2 Slow", "arrows", "up", 1],
  [30, "Arrows Moving Down · RVO x2 Slow", "arrows", "down", 1],
  [31, "V Moving Up · RVO x2 Slow", "letterV", "up", 1],
  [32, "V Moving Down · RVO x2 Slow", "letterV", "down", 1],
  [33, "Horizontal Diverging · RVO x2 Slow", "divergentStripes", "right", 1],
  [34, "Horizontal Converging · RVO x2 Slow", "convergentStripes", "left", 1],
  [35, "Vertical Diverging · RVO x2 Slow", "divergentStripes", "down", 1],
  [36, "Vertical Converging · RVO x2 Slow", "convergentStripes", "up", 1],
  [37, "Multiple Distortions Intersecting · RVO x2 Slow", "intersectingStripes", "multi", 1],
  [74, "Chequered Board Warp · RVO x2 Slow", "checkerboard", "warp", 1],
  [75, "RVO x2 Fast", "stripes", "right", 2],
];

const smoothVideos: Array<[number, string, number]> = [
  [49, "Smooth Pursuit · Slow Moving Target", 0.1],
  [50, "Smooth Pursuit · Moving Target", 0.2],
  [51, "Smooth Pursuit · Fast Moving Target", 0.5],
];

const correctiveVideos: Array<[number, string, BackgroundType, Direction]> = [
  [53, "Vertical Down", "none", "down"],
  [54, "Vertical Up", "none", "up"],
  [55, "Horizontal Left", "none", "left"],
  [56, "Horizontal Right", "none", "right"],
  [57, "Chequered Jiggle", "checkerboard", "jiggle"],
  [58, "Chequered Warp", "checkerboard", "warp"],
  [59, "Arrow Down", "arrows", "down"],
  [60, "Arrow Up", "arrows", "up"],
  [61, "V Down", "letterV", "down"],
  [62, "V Up", "letterV", "up"],
  [63, "Diagonal Bottom Left", "none", "bottom-left"],
  [64, "Diagonal Bottom Right", "none", "bottom-right"],
  [65, "Diagonal Top Left", "none", "top-left"],
  [66, "Diagonal Top Right", "none", "top-right"],
  [67, "Horizontal Converging", "convergentStripes", "left"],
  [68, "Horizontal Diverging", "divergentStripes", "right"],
  [69, "Vertical Diverging", "divergentStripes", "down"],
  [70, "Vertical Converging", "convergentStripes", "up"],
  [71, "Converging and Diverging", "intersectingStripes", "multi"],
];

export const protocols: Protocol[] = [
  {
    id: "base-vor-x1-h",
    sourceVideo: null,
    category: "RVO x1",
    module: MODULES.FIXED_TARGET,
    name: "RVO x1 horizontal",
    level: "Base",
    cue: "Mantené la mirada fija. Mové la cabeza de lado a lado.",
    head: "Sí: izquierda/derecha",
    eyes: "Fijos en el objetivo",
    background: { enabled: false, type: "none", direction: "right" },
    objective: { enabled: true, mode: "fixed", direction: "horizontal" },
    frequencyHz: 1,
    metronome: true,
  },
  {
    id: "base-vor-x1-v",
    sourceVideo: null,
    category: "RVO x1",
    module: MODULES.FIXED_TARGET,
    name: "RVO x1 vertical",
    level: "Base",
    cue: "Mantené la mirada fija. Mové la cabeza arriba y abajo.",
    head: "Sí: arriba/abajo",
    eyes: "Fijos en el objetivo",
    background: { enabled: false, type: "none", direction: "right" },
    objective: { enabled: true, mode: "fixed", direction: "vertical" },
    frequencyHz: 1,
    metronome: true,
  },
  {
    id: "guided-vor-cancel",
    sourceVideo: null,
    category: "Guiados",
    module: MODULES.FIXED_TARGET,
    name: "VOR cancellation guiado",
    level: "Intermedio",
    cue: "Mové cabeza, tronco y objetivo juntos. El punto queda centrado como guía.",
    head: "Cabeza + manos juntos",
    eyes: "Fijan el objetivo",
    background: { enabled: false, type: "none", direction: "right" },
    objective: { enabled: true, mode: "fixed", direction: "center" },
    frequencyHz: 0.8,
    metronome: true,
  },
  ...optokineticVideos.map(
    ([sourceVideo, title, patternType, direction]): Protocol => ({
    id: `okn-${sourceVideo}`,
    sourceVideo,
    category: "Optocinético",
    module: MODULES.OPTOKINETIC,
    name: title,
    level: sourceVideo <= 4 || sourceVideo >= 72 ? "Base" : sourceVideo <= 14 ? "Intermedio" : "Avanzado",
    cue: "Fondo geométrico repetitivo en movimiento continuo.",
    head: "Quieta o según indicación",
    eyes: "Fijar centro o tolerar flujo",
    background: { enabled: true, type: patternType, direction },
    objective: { enabled: false, mode: "none", direction: "center" },
    frequencyHz: direction === "jiggle" ? 2 : 1,
    metronome: false,
    }),
  ),
  ...vor2Videos.map(
    ([sourceVideo, title, patternType, direction, frequencyHz]): Protocol => ({
    id: `vor2-${sourceVideo}`,
    sourceVideo,
    category: "RVO x2",
    module: MODULES.VOR_X2,
    name: title,
    level: frequencyHz >= 2 ? "Avanzado" : "Intermedio",
    cue: "Cabeza en sentido contrario al objetivo. Metrónomo ligado a Hz.",
    head: "Contraria al objetivo",
    eyes: "Fijan objetivo móvil",
    background: { enabled: true, type: patternType, direction },
    objective: { enabled: true, mode: "moving", direction },
    frequencyHz,
    metronome: true,
    }),
  ),
  ...smoothVideos.map(
    ([sourceVideo, title, frequencyHz]): Protocol => ({
    id: `smooth-${sourceVideo}`,
    sourceVideo,
    category: "Seguimiento suave",
    module: MODULES.SMOOTH_PURSUIT,
    name: title,
    level: frequencyHz >= 0.5 ? "Avanzado" : frequencyHz <= 0.1 ? "Base" : "Intermedio",
    cue: "Seguí el objetivo en trayectoria continua tipo infinito/Lissajous.",
    head: "Quieta",
    eyes: "Seguimiento continuo",
    background: { enabled: false, type: "none", direction: "right" },
    objective: { enabled: true, mode: "smooth", direction: "lissajous" },
    frequencyHz,
    metronome: false,
    }),
  ),
  ...correctiveVideos.map(
    ([sourceVideo, title, patternType, direction]): Protocol => ({
    id: `saccade-${sourceVideo}`,
    sourceVideo,
    category: "Sacadas correctivas",
    module: MODULES.CORRECTIVE_SACCADES,
    name: title,
    level: sourceVideo <= 56 ? "Base" : sourceVideo <= 66 ? "Intermedio" : "Avanzado",
    cue: "El objetivo se teletransporta en la grilla exacta del metrónomo.",
    head: "Quieta",
    eyes: "Salto rápido al nuevo objetivo",
    background: { enabled: patternType !== "none", type: patternType, direction },
    objective: { enabled: true, mode: "saccade", direction },
    frequencyHz: 1,
    metronome: true,
    }),
  ),
];
